### ISSUE TITLE
Unallocated memory not removed from loop linked list structure

### ISSUE THREAD

**Issue by karlsharman** [linear-rpc/libtv#1]
https://github.com/linear-rpc/libtv/blob/3373e5100e579e7b3b3f28ae170ebd70f859b86a/src/tcp.c#L317
The uv_handle is freed, but it is still linked into the handle->loop->loop linked list (it is linked into the list in the uv_tcp_init function just above).

This causes memory corruption, because the memory that was associated with uv_handle could be allocated to something else in user-space - future adjustment of the linked list will corrupt that memory. 

Insert 'QUEUE_REMOVE(&uv_handle->handle_queue)' before the 'free(uv_handle);' command.

**Comment by MasayukiImanishi001** [comment]
Thank you for the Issue and PR.
I deleted "free(uv_handle)" and add "uv_close()" for preventing memory corruption because other error handling uses uv_close().

https://github.com/linear-rpc/libtv/commit/55fb5992f9f200732182bfef837f2d7142dbfbfd
